### ISSUE TITLE
BUG Persistent Audio HUD Triggers in Google Meet & Zoom Sessions

### ISSUE THREAD

**Issue by Bhanu1776** [Wouter01/MediaMate-Releases#47]
**Describe the bug**
I noticed something odd during my Google Meet & Zoom sessions. The audio HUD constantly triggers, even when I'm not touching any sound keys. Any insights on why this might be happening? It's disrupting my meetings and kinda frustrating.

**Comment by Wouter01** [comment]
This is likely happening because both apps are adjusting your volume, and MediaMate is reacting to that. A few things you could do to resolve this are:
- Set the event controller mode (general tab) for audio to "Keyboard", and disable "Show on external volume event" in the audio settings. This way, MediaMate will only show up when changing the volume through the keyboard buttons, and nothing else.
- Enable a focus filter when calling, and add the mediamate focus filter, so the audio hud does not show up when the focus is enabled

**Comment by RusackN1** [comment]
Hello @Wouter01 👋 I have the same issue but managed to actually understand the reason of why it occurs.

**Bug:** MediaMate (System Event Mode) reacts to Input Volume change besides Output Volume change, although it shouldn't. 

**Details:** Apps like Zoom are able to change mic's volume based on the volume of speaker. It happens automatically and at exactly the moment of change MediaMate interface shows up on the screen.
The interface disappears after every change, but sometimes Zoom isn't sure what volume to pick and it will change every 2-3 seconds, so the interface stays on screen and drains battery.

**How to replicate:** Go to System Settings -> Sound and try changing input volume (microphone). MediaMate will show up on the screen but won't indicate any change, because it indicates output volume level.

**My device:** MacBook Pro 16 M3 Max (MacOS 14.4 (23E214))

Is it fixable?

**Comment by Wouter01** [comment]
Thank you for looking into this, this is really valuable! Based on your info, I have made some changes which hopefully fix this issue. Mainly, the HUD shouldn't be triggered anymore on microphone volume changes. An update will be released soon which includes this fix!

**Comment by RusackN1** [comment]
Will also need to check battery drain, because if the interface doesn't show up but the app is still reacting to mic volume change, this is less than ideal :)

**Comment by Wouter01** [comment]
A new update has been released which should fix the issue. Could you check and, if fixed, close the issue?

**Comment by RusackN1** [comment]
Fixed. Kind of.
Power consumption is still there when I change input (mic) volume or sound effects volume. 
~10 times less compared with output volume change + interface. (Activity Monitor shows ~7 against ~72)

Thank you.

**Comment by Wouter01** [comment]
I wasn't aware that there was a large power consumption because of the issue. If I understand you correctly, the new update now has 7, and the old had 72? Are these CPU usage numbers?

**Comment by RusackN1** [comment]
no, the issue didn't cause any extra power consumption. It's just interesting that even though input volume slider doesn't trigger volume bar in MediaMate anymore, the app itself still reacts to it and consumes power, though only a little.
these are energy impact numbers

72 is the number when I change output volume level and the MediaMate Bar appears on screen
7 is the number when I change input volume level / sound effects level and nothing appears on the screen

I know this is a minor thing, but if you have many small apps consuming this much persistently, battery dies faster. It would be perfect if MediaMate just completely ignored any input volume change and sound effects change.

**Comment by Wouter01** [comment]
I get that, but it doesn't seem like it's possible to do that in this case. In order to get updates about the volume, I have to observe *all* of it. Then, I have to filter out the microphone events, which take processing time.
When you want to maximize the efficiency of the app, I suggest using the Keyboard event mode. This should be the most efficient option (And if you turn off "Extended keyboard support", it'll be even more efficient).
